function plot_reproductive_rate(t,R_e)

% This function provides a graph showing:
% - t vs R_e

% It saves the figure generated in the folder "GRAPHS" with the name
% "REPRODUCTIVE_RATE.jpg"

% INPUT PARAMETERS:
% - t: nx1 column vector (n generic) generated by solving the ODE SIR model, being the
%   time vector of the former
% - R_e: nx1 column vector (n generic), R_e = A/B * S(t), containing the value of the 
%   reproductive rate as function of time

% The function generates one plot, a legend, draws a grid on the canva and titles the axes.

    figure('units','normalized','outerposition',[0 0 1 1]);

    plot(t,R_e,"o","LineWidth",1);
    
    legend("Reproductive rate","Location","east");  
    
    grid on;
    xlabel("Time [days]","FontWeight","bold");
    ylabel("Reproductive rate","FontWeight","bold");

    saveas(gcf,"GRAPHS/REPRODUCTIVE_RATE.jpg");

end
