function [dydt] = sir(t,y,A,B)

% This function provides the structure of the system of Ordinary
% Differential Equations describing the SIR model. 

% INPUT PARAMETERS:
% - t: nx1 column vector (n generic) generated by solving the ODE SIR model, being the
%   time vector of the former
% - y: nx3 matrix (n generic) being the ODE system solution of the SIR model 
%   (y(:,1) = S(t) susceptibles, y(:,2) = I(t) infected, y(:,3) = R_m(t) total removed )
% - A: float positive number, being the exponential increasing parameter of
%   the SIR model
% - B: float positive number, being the exponential decreasing parameter of
%   the SIR model

% OUTPUT PARAMETERS:
% - dydt: 3xn matrix (n generic). Each row contains one specific differential equation of the SIR model 

% The SIR variables are initialized, then dydt is initialized as a 3x1
% matrix of zeros, to be filled with the differential equations.

    Susc = y(1);
    Infec = y(2);

    dydt = zeros(3,1);
    dydt(1) = -A*Susc*Infec;
    dydt(2) = A*Susc*Infec - B*Infec;
    dydt(3) = B*Infec;

end
