function test_normalization_zero_data()

% This test verifies that, provided a dataset of zeros, the function normalization can't handle
% the dataframe. 

% INIT PARAMETERS:
% - duration: int positive number defining the analysis time window
% - data: duration x 10 matrix of zeros

% Errors arise since the normalization should be performed by dividing by 
% normalization_fac = max(total_infected) = 0 and the vectors generated by normalization are empty.

    
    addpath(genpath(fullfile(pwd,"..","FUNCTIONS")));
    
    duration = 161;
    data = zeros(duration, 10);
    [new_positives, active_infections, total_removals, total_infected, deaths, recovers] = normalization(data,duration);
     
    assert(all(total_infected == zeros(duration, 1)),"Error: provided dataset of zeros, can't divide by 0");
    assert(all(new_positives == zeros(duration, 1)),"Error: provided dataset of zeros, new_positives is empty");
    assert(all(active_infections == zeros(duration, 1)),"Error: provided dataset of zeros, active_infections is empty");
    assert(all(total_removals == zeros(duration, 1)),"Error: provided dataset of zeros, total_removals is empty");
    assert(all(deaths == zeros(duration, 1)),"Error: provided dataset of zeros, deaths is empty");
    assert(all(recovers == zeros(duration, 1)),"Error: provided dataset of zeros, recovers is empty");
  
end

   